
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.jbrod.graficador.analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LINEA = 19;
  public static final int MULTIPLICACION = 3;
  public static final int DIVISION = 4;
  public static final int SUMA = 5;
  public static final int CURVA = 20;
  public static final int ANIMAR = 21;
  public static final int CAFE = 18;
  public static final int CUADRADO = 26;
  public static final int OBJETO = 22;
  public static final int PARC = 8;
  public static final int VERDE = 13;
  public static final int PARA = 7;
  public static final int ROJO = 11;
  public static final int GRAFICAR = 24;
  public static final int AMARILLO = 12;
  public static final int COMA = 9;
  public static final int EOF = 0;
  public static final int TURQUESA = 16;
  public static final int MORADO = 14;
  public static final int POLIGONO = 28;
  public static final int error = 1;
  public static final int NUMERO = 2;
  public static final int IDENTIFICADOR = 29;
  public static final int CIRCULO = 25;
  public static final int AZUL = 10;
  public static final int ANTERIOR = 23;
  public static final int NEGRO = 17;
  public static final int RECTANGULO = 27;
  public static final int NARANJA = 15;
  public static final int RESTA = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMERO",
  "MULTIPLICACION",
  "DIVISION",
  "SUMA",
  "RESTA",
  "PARA",
  "PARC",
  "COMA",
  "AZUL",
  "ROJO",
  "AMARILLO",
  "VERDE",
  "MORADO",
  "NARANJA",
  "TURQUESA",
  "NEGRO",
  "CAFE",
  "LINEA",
  "CURVA",
  "ANIMAR",
  "OBJETO",
  "ANTERIOR",
  "GRAFICAR",
  "CIRCULO",
  "CUADRADO",
  "RECTANGULO",
  "POLIGONO",
  "IDENTIFICADOR"
  };
}

